---
role_name_check: 1
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-debian12-ansible}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
