---
name: Molecule Tests
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: blackieops.postgresql

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        distro:
          - geerlingguy/docker-rockylinux9-ansible:latest
          - geerlingguy/docker-debian12-ansible:latest
          - geerlingguy/docker-ubuntu2204-ansible:latest
          - ghcr.io/blackieops/docker-sles15-ansible:latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: blackieops.postgresql

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
